---
services:
  speedtest_monitor:
    build:
      context: .
      dockerfile: Dockerfile
    image: speedtest_monitor:latest
    environment:
      - SPEEDTEST_LOG_LEVEL=${SPEEDTEST_LOG_LEVEL}
      - SPEEDTEST_LOG_PATH=${SPEEDTEST_LOG_PATH}
      - SPEEDTEST_DB_HOSTNAME=${SPEEDTEST_DB_HOSTNAME}
      - SPEEDTEST_DB_USERNAME=${SPEEDTEST_DB_USERNAME}
      - SPEEDTEST_DB_PASSWORD=${SPEEDTEST_DB_PASSWORD}
      - SPEEDTEST_DB_SCHEMA=${SPEEDTEST_DB_SCHEMA}
      - SPEEDTEST_DB_TABLE=${SPEEDTEST_DB_TABLE}
    volumes:
      - /var/log/speedtest_monitor:/app/log:z