{
 "title": "Speedtest Monitor",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    { "expression": "$Download * 0.000008", "type": "math" },
    { "expression": "$Upload * 0.000008", "type": "math" }
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "expression": "$A * 0.000008", "type": "math" },
    { "expression": "$B * 0.000008", "type": "math" },
    { "expression": "$C * 0.000008", "type": "math" }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A * 0.000008", "type": "math" },
    { "expression": "$B * 0.000008", "type": "math" },
    { "expression": "$C * 0.000008", "type": "math" }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  min(ping_latency) AS \"Best\"\nFROM speedtest\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  max(ping_latency) AS \"Worst\"\nFROM speedtest\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  avg(ping_latency) AS \"Average\"\nFROM speedtest\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  ping_latency\nFROM speedtest\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  GREATEST(download_elapsed, upload_elapsed) AS \"Duration\"\nFROM speedtest\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Test Results",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  (download_bandwidth * 0.000008) as download_throughput, (upload_bandwidth * 0.000008) as upload_throughput, ping_latency, server_id, server_host, server_port, server_ip\nFROM speedtest\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  }
 ]
}